sudo: required
language: java
jdk:
  - openjdk8

services:
  - docker
  
before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t eureka-service .
  - docker tag eureka-service:latest
  - docker push anupamattrey/eureka-service:latest
  
notifications:
  email:
    recipients:
      - anupam.attrey@hotmail.com
    on_success: always # default: change
    on_failure: always # default: always

