sudo: required
language: java
jdk:
  - openjdk8

services:
  - docker
  
env:
  global:
  #- secure: "encrypted-sonar-token"
  #- secure: "encrypted-dockerhub-username"
  #- secure: "encrypted-dockerhub-password"
  #- secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}
  
before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - echo $DOCKER_USER
  - export IMAGE_NAME=anupamattrey/discovery-service
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
  
notifications:
  email:
    recipients:
      - anupam.attrey@hotmail.com
    on_success: always # default: change
    on_failure: always # default: always

