sudo: required
language: java
jdk:
  - openjdk8

services:
  - docker
  
before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t discovery-service-0.0.1-SNAPSHOT .
  - docker tag discovery-service:0.0.1-SNAPSHOT
  - docker push anupamattrey/discovery-service:0.0.1-SNAPSHOT
  
notifications:
  email:
    recipients:
      - anupam.attrey@hotmail.com
    on_success: always # default: change
    on_failure: always # default: always

