spring:  application:    name: discovery-service  profiles:    active: development  cloud:    config:      uri:      - http://localhost:8888 server:
  port: ${PORT:8761}


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false    serviceUrl:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:  endpoints:    web:      exposure:        include: health,info,metrics,prometheus                 